# setup vars
environ:                        "prod" # dev || stage || prod
login_user_passphrase:          "{{ vault_login_user_passphrase }}"

# assetstore vars
remote_stores_available:        true
stores_fstab:
- name:   "/mnt/dspace/storage"
  src:    "sam.mse.jhu.edu:/apps/dspace"
  fstype: "nfs"
  opts:   "rw,tcp,intr,noatime"
  state:  "mounted"

# apache vars
ssl_certificate_file:           "{{ vault_ssl_certificate_file }}"
ssl_certificate_key_file:       "{{ vault_ssl_certificate_key_file }}"
ssl_certificate_chain_file:     "{{ vault_ssl_certificate_chain_file }}"

# db vars
dspace_db_address:              "psql03.{{ domainname }}"

# config vars
dspace_hostname_override:       "jscholarship.library.jhu.edu"
