# setup vars
environ:                "dev" # dev || stage || prod
debugging:              true
login_user_passphrase:  "{{ vault_login_user_passphrase }}"

# db vars
dspace_ip:                  "{{ hostvars[groups['app'][0]]['ansible_all_ipv4_addresses'][0] }}"
dspace_db_ip:               "{{ hostvars[groups['db'][0]]['ansible_all_ipv4_addresses'][0] }}"
# dspace_db_ip:   "{{ hostvars[groups['db'][0]]['ansible_eth1']['ipv4']['address'] }}"

dspace_address:             "{{ dspace_ip }}"
dspace_db_address:          "{{ dspace_db_ip }}"

# apache vars
domainname:                 "test"
ssl_self_sign_cert:         true

# TODO: move to all (?)
postgres_version_major:     9
postgres_version_minor:     6
postgres_extra_packages:
  - "postgresql-contrib"
postgres_extensions:
  - "pgcrypto"
# admin vars
dspace_admins:              "{{ vault_dspace_admins }}"
