# setup vars
environ:                "dev" # dev || stage || prod
debugging:              true

# SSH vars
login_group:            "{{ lookup('ini', 'login_group section=dev file=~/.ansible.ini default=' + login_user ) }}"
login_password:         "{{ lookup('ini', 'login_password section=dev file=~/.ansible.ini') }}"
login_user_grant_sudo:  true

# db vars
dspace_ip:                  "{{ hostvars[groups['app'][0]]['ansible_all_ipv4_addresses'][0] }}"
dspace_db_ip:               "{{ hostvars[groups['db'][0]]['ansible_all_ipv4_addresses'][0] }}"

# data transform queries
db_transform_queries:       []

# apache vars
# dspace_name:                "JScholarship-{{ environ | title }}"
# TODO: move to dspace-{{ environ }}, for consistency with other environments
hostname:                   "{{ dspace_name | lower }}"
domainname:                 "test"
ssl_self_sign_cert:         true
ssl_support_legacy_clients: false
PASS_config:                false
# dspace_hostname_override:   "dspace-dev.test"

# admin vars
dspace_admins:              "{{ vault_dspace_admins }}"
# dspace_local_config_template: "templates/local-override.cfg.j2"
# loglevel_dspace:            "DEBUG"

# upgrade vars
dspace_backup_default_assetstore: true

# testing vars
set_up_tests:   false
